language: node_js
node_js:
  - "8.11.1"
services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
  - psql -c 'create user node with password root;' -U postgres
cache:
  directories:
    - "node_modules"
branches:
  only:
    - master
    - develop
after_success:
  - npm run coverage